### ISSUE TITLE
Elasticsearch integration with newrelic

### ISSUE THREAD

**Issue by Akanshu9990** [newrelic/nri-elasticsearch#213]
I can't integrate my elasticsearch cluster with newrelic. My elastic search is running as a operator inside by redhat openshift cluster.

For newrelic i have a different namespace and all metrics from pods and nodes are being collected by newrelic perfectly, It's just elasticsearch creating a problem.

i have tried with this documentation of newrelic only https://github.com/newrelic/nri-elasticsearch/blob/master/elasticsearch-config.yml.k8s_sample

Also my newrelic kubelet agent pods are running as a Daemonset and i am trying all of this via helm chart.

I can see this log inside one of my pod level=info msg="Integration health check finished with success" component=integrations.runner.Runner integration_name=nri-elasticsearch runner_uid=da9ef8411c but cant see anything in newrelic .

**Comment by davidgit** [comment]
Hi @Akanshu9990,

The next best step is to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs. 

Please provide a link to this GitHub issue when submitting your community post or support ticket.

Thanks!

**Comment by iamvishnuks** [comment]
Try this configuration below,
```
newrelic-infrastructure:
  enabled: true
  integrations:
    elasticsearch-config.yml:
      # Run auto discovery to find pods with label "app=elasticsearch"
      # https://docs.newrelic.com/docs/integrations/host-integrations/installation/container-auto-discovery
      discovery:
        command:
          --namespaces: elastic-system
          exec: /var/db/newrelic-infra/nri-discovery-kubernetes
          match:
            label.app: elasticsearch
      integrations:
        - name: nri-elasticsearch
          env:
            CLUSTER_ENVIRONMENT: aks-cargoesflow-prod-dr
            # Use the discovered IP as the host address
            HOSTNAME: ${discovery.ip}
            # Set the elasticsearch node name to the discovered pod name
            LOCAL_HOSTNAME: ${discovery.podName}
            USERNAME: elastic
            PASSWORD: xxxxxx
            PORT: 9200
            TIMEOUT: 30
            METRICS: 1
            USE_SSL: true
            TLS_INSECURE_SKIP_VERIFY: true
```

Add verbose log if you are still seeing error to troubleshoot further
```
# To enable verboseLog for newrelic-infrastructure only
newrelic-infrastructure:
  verboseLog: true
```

We faced similar issue and it was because elasticsearch endpoint was listening on https while the newrelic agent tried connecting on http. Adding USE_SSL and TLS_INSECURE_SKIP_VERIFY params fixed the issue.
